---
site: "Rickshaw"
url: "https://busterbenson.github.io/rickshaw"
baseurl: '/rickshaw'
title: 'Rickshaw'
description: 'A group blog thing.'
twitter:
  username: '@buster'
  card: 'summary'
  creator: 'buster'
author:
  twitter: '@buster'
  name: 'Buster Benson'
  avatar: 
  url: 'https://busterbenson.com'
  twitter: '@buster'
twitter: 
  username: '@buster'
  card: 'summary'
  creator: 
permalink: 'pretty'
highlighter: 'none'
exclude:
  - '.jekyll-cache'
  - 'Gemfile'
  - 'Gemfile.lock'

compress_html:
  clippings: 'all'
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: '_sass'
  style:    ':compressed'

plugins:
  - 'jekyll-paginate'
  - 'jekyll-seo-tag'
  - 'jekyll-sitemap'  

collections:
  pages:
    output: true
    permalink: '/:name'
  posts:
    output: true
    permalink: '/:slug'
  tags:
    output: true
    permalink: '/tag/:path/'

defaults:
  - scope:
      path: "/rickshaw"
    values:
      layout: "default"
  - scope:
      path: "/pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "/posts"
      type: "posts"
    values:
      layout: "post"
