site: Rickshaw
url: https://busterbenson.github.io/rickshaw
baseurl: '/rickshaw'
title: Rickshaw
description: A group blog thing.
twitter:
  username: '@buster'
  card: summary
  creator: buster
author:
  twitter: '@buster'
  name: Buster Benson
  avatar: 
  url: https://busterbenson.com
  twitter: '@buster'
twitter: 
  username: '@buster'
  card: summary
  creator: 
permalink: pretty
highlighter: non
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style:    :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  tags:
    output: true
    permalink: /tag/:path/

defaults:
  -
    scope:
      path: "/rickshaw"
    values:
      layout: "default"
  -
    scope:
      path: "/pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "/posts"
      type: "posts"
    values:
      layout: "post"

prose:
  rooturl: '_posts'
  siteurl: 'https://busterbenson.github.io/rickshaw/'
  media: 'assets/media'
  ignore:
    - /.github
    - /.jekyll-cache
    - /_includes
    - /_layouts
    - /_plugins
    - /_sass
    - .gitignore
    - 404.html 
    - _config.yml
    - atom.xml
    - favicon.png
    - feed.json
    - Gemfile
    - Gemfile.lock
    - index.html
    - LICENSE.md 
    - robots.txt
  users: 
    - login: "busterbenson"
      user: "Buster"
      profile_link: "/p/buster"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          text: "Title"
          value: ""
      - name: "User"
        field:
          element: "hidden"
          value: CURRENT_USER
      - name: "description"
        field:
          element: "text"
          text: "Summary"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: Thoughts
              value: thoughts
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
